### ISSUE TITLE
Action is unable to display AWS CloudWatch Logs from the custom log stream

### ISSUE THREAD

**Issue by lsuutari19** [dark-mechanicum/aws-codebuild#145]
I haven't managed to make this action output the correct AWS CloudWatch logs, it does correctly start the codebuild run, find the log stream and proceed to wait for the run to finish before continuing the workflow. 

    - name: Run CodeBuild project
        id: aws-codebuild-run-build
        uses: dark-mechanicum/aws-codebuild@v1
        with:
          projectName: 'project'
          buildStatusInterval: 5000
          logsUpdateInterval: 5000
          waitToBuildEnd: true
          displayBuildLogs: true
        env:
          CODEBUILD__sourceVersion: "source"

![image](https://github.com/dark-mechanicum/aws-codebuild/assets/55877405/9aa069c2-c52b-4bbf-afe0-9f6f1baf9fb9)
![image](https://github.com/dark-mechanicum/aws-codebuild/assets/55877405/273f8341-e8d0-4b24-adce-c0301e7e4c5c)

One way to display them correctly was to use the logsConfigOverride option in the buildspec, but this would then overwrite the other log environment details such as the S3 location, which would have to then be manually set in the action call, which isn't ideal in this situation, since everything should be provided from the environment variables. With this option set it will set the log stream location to action's default versus from the custom log location that is in the format provided in the above. 

          "logsConfigOverride": {
            "cloudWatchLogs": {
              "status": "ENABLED"
            },
            "s3Logs": {
              "status": "ENABLED",
              "location": "arn:aws:s3:::bucket"
            }
          }

Here are the logs settings for the project:

![image](https://github.com/dark-mechanicum/aws-codebuild/assets/55877405/abe724e8-f90a-4ce5-baf9-97d6b8304a90)

And here are the required policies for the deployment role:

        {
            "Action": [
                "codebuild:StartBuild",
                "codebuild:StopBuild",
                "codebuild:BatchGetBuilds",
                "codebuild:ListBuildsForProject"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": "logs:GetLogEvents",
            "Resource": "*",
            "Effect": "Allow"
        }

**Comment by akazakou** [comment]
@lsuutari19 Thank you for providing the report. I'll do my best to find some time to address the issue, but I would greatly appreciate it if you could create a pull request (PR) to expedite the resolution of the problem. Your collaboration would be very helpful in resolving the issue promptly. Thanks again!

**Comment by akazakou** [comment]
@lsuutari19 One potential solution, if you prefer using only environment variables, is to define a build spec override using an environment variable such as CODEBUILD__logsConfigOverride__cloudWatchLogs__status. Alternatively, you can try using a JSON object for this purpose. Both approaches could help address the issue effectively.

```yaml
- name: Run CodeBuild project
    id: aws-codebuild-run-build
    uses: dark-mechanicum/aws-codebuild@v1
    with:
      projectName: 'project'
      buildStatusInterval: 5000
      logsUpdateInterval: 5000
      waitToBuildEnd: true
      displayBuildLogs: true
    env:
      CODEBUILD__sourceVersion: "source"
      CODEBUILD__logsConfigOverride__cloudWatchLogs: '{"status":"ENABLED"}'
```
