### ISSUE TITLE
Action is not waiting for codebuild run to end

### ISSUE THREAD

**Issue by ozgenbaris1** [dark-mechanicum/aws-codebuild#39]
I couldn't manage to make this action wait for codebuild run to end. It only starts the codebuild run and proceeds to the next step without waiting for the final result. I'm sharing the yml file snippet for the step and its output. Any help would be much appreciated.

```
      - name: Run CodeBuild
        uses: dark-mechanicum/aws-codebuild@v1
        env:
          CODEBUILD__sourceVersion: "publish"
        with:
          projectName: ${{ env.PROJECT_NAME }}
```

![image](https://user-images.githubusercontent.com/32235421/179706185-43e867ae-d357-4dbd-bec4-82cf4c071a2a.png)

**Comment by ozgenbaris1** [comment]
I don't know but can it be related to [StartBuildInput](https://github.com/dark-mechanicum/aws-codebuild/blob/3f4d32042fc3a9da1e3746a25c0e0749ed236b7b/src/codebuildjob.ts#L15)?

I think [here](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-codebuild/modules/startbuildinput.html) the **`reportBuildStatusOverride`** property is not set and it's _undefined_

Maybe explicitly setting it to `true` may help?

> reportBuildStatus — (Boolean)
> Set to true to report the status of a build's start and finish to your source provider. This option is valid only when your source provider is GitHub, GitHub Enterprise, or Bitbucket. If this is set and you use a different source provider, an invalidInputException is thrown.
> 
> To be able to report the build status to the source provider, the user associated with the source provider must have write access to the repo. If the user does not have write access, the build status cannot be updated. For more information, see [Source provider access](https://docs.aws.amazon.com/codebuild/latest/userguide/access-tokens.html) in the CodeBuild User Guide.
> 
> The status of a build triggered by a webhook is always reported to your source provider.
> 
> If your project's builds are triggered by a webhook, you must push a new commit to the repo for a change to this property to take effect.

**Comment by akazakou** [comment]
@ozgenbaris1 potentially you can set it from your implementation of GitHub Action usage like:

```yaml
  - name: Run CodeBuild
    uses: dark-mechanicum/aws-codebuild@v1
    env:
      CODEBUILD__sourceVersion: "publish"
      CODEBUILD__reportBuildStatusOverride: "true"
    with:
      projectName: ${{ env.PROJECT_NAME }}
```

Try this one. I will be happy to get any response about it :)

**Comment by akazakou** [comment]
@ozgenbaris1 I've applied some fixes that will resolve wait for job status without logs. Try to use `main` version instead of `v1` to verify is that will resolve your issue.

```yaml
  - name: Run CodeBuild
    uses: dark-mechanicum/aws-codebuild@main
    env:
      CODEBUILD__sourceVersion: "publish"
    with:
      projectName: ${{ env.PROJECT_NAME }}
```
