### ISSUE TITLE
Generated build link has masked value for AWS AccountId

### ISSUE THREAD

**Issue by Fraznist** [dark-mechanicum/aws-codebuild#68]
The Codebuild Build link is generated from the following template
```typescript
https://${region}.console.aws.amazon.com/codesuite/codebuild/${accountID}/projects/${projectName}/build/${encodeURIComponent(build.id as string)}/?region=${region}
```
the `accountID` variable is replaces with `***` instead of the actual AWS account id, thus generating a broken link.

**Comment by akazakou** [comment]
Hi @Fraznist . That issue relates to the `aws-actions/configure-aws-credentials`. That action masks all credentials and it affects the summary section. To avoid this, you can use Environment Variables without `aws-actions/configure-aws-credentials`.

I have an idea of how to work with URLs like bit.ly service. But I'm not sure it will be an acceptable solution...

**Comment by akazakou** [comment]
I've created that service and feature #79 
It is optional, so anyone who wants can create his own redirect service or use my example "https://cloudaws.link/r/"

**Comment by akazakou** [comment]
@Fraznist I've added new GitHub Action Input support. Now you can use `redirectServiceURL` input to define a service that will work with Base64 Encoded URLs to avoid masking of AWS credentials. You can check the behavior of it in my [release verification steps](https://github.com/dark-mechanicum/aws-codebuild/actions/runs/2996094653)

```yaml
- name: Executing AWS CodeBuild task
  uses: dark-mechanicum/aws-codebuild@v1
  with:
    projectName: '<your-aws-codebuild-job-name-here>'
    redirectServiceURL: 'https://cloudaws.link/r/'
```
